adobe/helix-status

- src/index.js
- test/index.test.js
> fix(status): always send 200

- src/index.js
- test/index.test.js
> fix(status): include x-version header

- package-lock.json
- package.json
- src/index.js
- test/index.test.js
> fix(status): add timeout for backend checks

- package-lock.json
- package.json
- test/index.test.js
> Greenkeeper/@adobe/openwhisk action builder 1.2.1

- package-lock.json
- package.json
> fix(package): downgrade snyk to 1.199.0

- package-lock.json
- package.json
> Greenkeeper/lint staged 9.2.1

- README.md
- package.json
- src/index.js
- test/fixtures/recordings/Index-Tests_647266286/index-function-returns-error-status-code_3394645443/recording.har
- test/index.test.js
BREAKING CHANGE: Returns error Http status on error (Standard Http check) instead of always 200
(Custom Http check)
fix #21
> feat(index): Return error status code on error (standard Http check)

- package-lock.json
- package.json
- src/index.js
- test/index.test.js
> fix(user-agent): fix user agent version strings

- src/bin.js
> fix(monitoring): remove deprecated locations, reduce overall number

- src/bin.js
> fix(monitoring): readd all AWS locations

- src/statuspage.js
> fix(monitoring): missing alias for --page_id (#54)

- package.json
Fix https://github.com/adobe/helix-home/issues/13
> refactor(monitoring): helix-status to become monitor for I/O Runtime

- README.md
issue #63  
typo fixes :
commited -> committed
slighly -> slightly
intented -> intended
> update readme.md - typo fixes

- README.md
- src/statuspage.js
> feat(monitoring): update statuspage component group and description

- .circleci/config.yml
See https://github.com/adobe/helix-continuous/issues/38
> fix(ci): correct tool path

- README.md
- src/newrelic/monitor_script.js
- src/newrelic/synthetics.js
> feat(monitoring): use namespace specific wsk auth (#89)

- .circleci/config.yml
- package.json
- src/newrelic.js
- src/newrelic/synthetics.js
- src/statuspage.js
See https://github.com/adobe/helix-home/issues/72 for details.
> refactor(monitoring): move config from package.json to .circleci/config.yml

- .github/workflows/release.yml
> build(actions): add GitHub action for semantic release comment bot

- docs/API.md
- package-lock.json
- package.json
- src/index.js
- test/fixtures/recordings/Index-Tests_647266286/wrap-function-supports-request-options-check-with-functions_4061816471/recording.har
- test/index.test.js
- test/probot.test.js
> Remove xml status

- package-lock.json
- package.json
- src/index.js
- test/fixtures/recordings/Index-Tests_647266286/wrap-function-supports-request-options-check-with-functions_4061816471/recording.har
- test/fixtures/recordings/Index-Tests_647266286/wrap-function-supports-request-options-check_3738071926/recording.har
- test/index.test.js
- test/probot.test.js
> feat(status): use helix-fetch instead of request

- .circleci/config.yml
- package.json
See https://github.com/adobe/helix-ops/issues/108
> chore(deps): remove helix-ops dependency

- .circleci/config.yml
- .github/workflows/main.yml
- .github/workflows/semver-check.yaml
- .releaserc.js
- README.md
> feat: rename default branch from "master" to "main"

- .circleci/config.yml
- .github/workflows/semantic-release.yaml
@trieloff trying to deploy the action to runtime with the github action. I don't want to try it out...
i'll test it with the next update to status :-)
> chore: use github action to deploy to npm

- src/index.js
- test/probot.test.js
> fix(probot): adjust to new probot version

- package-lock.json
- package.json
> chore(deps): bump helix-fetch

- package-lock.json
- src/index.js
- test/index.test.js
> fix: use stateless fetch context

- README.md
> `wrap` renamed to `helixStatus` in v10
